name: Notify external contributions
on:
  issues:
    types: [opened]
  discussion:
    types: [created]
  pull_request:
    types: [opened,reopened,review_requested,ready_for_review]

jobs:
  notify-external-contributions:
    if: github.repository_owner == 'betterscientificsoftware'
    runs-on: ubuntu-latest
    steps:
      - name: Check user for team affiliation
        uses: tspascoal/get-user-teams-membership@v2
        id: teamAffiliation
        with:
          username: ${{ github.actor }}
          # 'bssw-editorial-board'
          team: 'mcm86-temp-test-team'
          GITHUB_TOKEN: ${{ secrets.TEAM_MEMBERSHIP_PAT }}
      - name: Stop workflow if user is no member
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == 'false' }}
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{ secrets.MCM86_MAIL_USERNAME }}
          # Optional (recommended) mail server password:
          password: ${{ secrets.MCM86_MAIL_PASSWORD }}
          # Required mail subject:
          subject: External contribution detected
          # Required recipients' addresses:
          # to: bssw-editorial@lists.mcs.anl.gov
          to: miller86@llnl.gov
          # Required sender full name (address can be skipped):
          from: notify-external-contrib.yml bssw.io action
          # Optional plain body:
          body: ${{ github.actor }} created ${{ github.event.issue.number }} ${{ github.event.issue.html_url }}
      - name: Debug
        uses: hmarr/debug-action@v2
