name: Notify external contributions
on:
  issues:
    types: [opened]
  discussion:
    types: [created]
  pull_request:
    types: [opened,reopened,review_requested,ready_for_review]

jobs:
  notify-external-contributions:
    if: github.repository_owner == 'betterscientificsoftware'
    runs-on: ubuntu-latest
    steps:
      - name: Check user for team affiliation
        uses: tspascoal/get-user-teams-membership@v2
        id: teamAffiliation
        with:
          username: ${{ github.actor }}
          # 'bssw-editorial-board'
          team: 'mcm86-temp-test-team'
          GITHUB_TOKEN: ${{ secrets.TEAM_MEMBERSHIP_PAT }}
      - name: Stop workflow if user is no member
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == false }}
        uses: cinotify/github-action@main
        with:
          to: 'bssw-editorial@lists.mcs.anl.gov'
          subject: 'BSSw External Submission'
          body: 'This is a notification from GitHub actions.'
